title: MA Qi's Homepage
page-top-title: MA Qi
# top-section-bg-text: Psychology
home-subtitle: MA Qi&ensp;|&ensp;mqqq3333&ensp;|&ensp;马琦
copyright-text: "&copy; MA Qi 2025-2026. All Rights Reserved."
